version: '3.1'
services:
  mongo:
    image: mongo
    ports:
    - '27017:27017'
    command: --serviceExecutor adaptive
  finance-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=finance
      - RABBITMQ_DEFAULT_PASS=finance
